dist: xenial
language: generic
sudo: required
services:
  - docker
before_install:
  - docker pull couchdb:latest
  - docker run --network=host -d -it -e COUCHDB_USER=admin -e COUCHDB_PASSWORD=1234 -p 5984:5984 couchdb:latest
  - docker pull crystallang/crystal:nightly
script:
  - docker run --network=host -v ${PWD}:/x -w /x crystallang/crystal:nightly bash -c "/usr/bin/shards install"
  - docker run --network=host -v ${PWD}:/x -e "TEST_DB=http://admin:1234@localhost:5984" -w /x crystallang/crystal:nightly bash -c "/usr/bin/crystal spec"
